spring.datasource.url=jdbc:h2:file:./data/finsight-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

testing.app.secret=dsnfljndfgknsfdgsfdg
testing.app.lifetime=3600000

ai-service.base-url=http://localhost:8000
