from enum import Enum


class PatternType(str, Enum):
    EXPENSES_EXCEED_INCOME = "EXPENSES_EXCEED_INCOME"
    HIGH_CATEGORY_CONCENTRATION = "HIGH_CATEGORY_CONCENTRATION"
    HIGH_TOP3_CONCENTRATION = "HIGH_TOP3_CONCENTRATION"
    LARGE_SINGLE_EXPENSE = "LARGE_SINGLE_EXPENSE"
    FREQUENT_SMALL_EXPENSES = "FREQUENT_SMALL_EXPENSES"
    NO_INCOME = "NO_INCOME"