from enum import Enum


class PatternType(str, Enum):
    EXPENSES_EXCEED_INCOME = "EXPENSES_EXCEED_INCOME"
    HIGH_CONCENTRATION = "HIGH_CONCENTRATION"
    TOP3_DOMINANCE = "TOP3_DOMINANCE"
    LARGE_SINGLE_EXPENSE = "LARGE_SINGLE_EXPENSE"
    FREQUENT_SMALL_EXPENSES = "FREQUENT_SMALL_EXPENSES"
    NO_INCOME = "NO_INCOME"