from enum import Enum


class InsightType(str, Enum):
    CATEGORY_STRUCTURE = "CATEGORY_STRUCTURE"
    INCOME_EXPENSE_RATIO = "INCOME_EXPENSE_RATIO"
    LARGE_EXPENSE = "LARGE_EXPENSE"
    SMALL_EXPENSES = "SMALL_EXPENSES"
    NO_INCOME = "NO_INCOME"
    HIGH_CONCENTRATION = "HIGH_CONCENTRATION"
    GENERAL = "GENERAL"